version: '2'
services:
  rss:
    build:
      context: .
    environment:
      MONGO_HOST: mongodb://mongo:27017
    volumes:
      - .:/alerts-rss
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo:
