version: '2'
services:
  cassandra:
    image: cassandra:latest
    volumes:
      - cassandra:/var/lib/cassandra
    ports:
      - "9042:9042"
  elasticsearch:
    image: elasticsearch:latest
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  elasticsearch:
  cassandra:
